require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StudentSurveysController, type: :controller do

  include Devise::TestHelpers

  before(:each) do
    @student=FactoryGirl.create(:student)
    @student.confirm!
    sign_in @student
  end


  # This should return the minimal set of attributes required to create a valid
  # StudentSurvey. As you add validations to StudentSurvey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:student_survey)
  }
    
  let(:workshop){
    FactoryGirl.create(:given_workshop, free: true)
  }


  let(:invalid_attributes) {
    FactoryGirl.attributes_for(:invalid_student_survey)
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StudentSurveysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  #describe "GET #index" do
  #  it "assigns all student_surveys as @student_surveys" do
  #    student_survey = StudentSurvey.create! valid_attributes
  #    get :index, {}, valid_session
  #    expect(assigns(:student_surveys)).to eq([student_survey])
  #  end
  #end

  describe "GET #show" do
    it "assigns the requested student_survey as @student_survey" do
      Enrollment.create!(workshop: workshop, student: @student)
      student_survey = StudentSurvey.create! valid_attributes.merge({workshop: workshop, student: @student})
      get :show, {:id => student_survey.to_param}, valid_session
      expect(assigns(:student_survey)).to eq(student_survey)
    end
  end

  describe "GET #new" do
    it "assigns a new student_survey as @student_survey" do
      get :new, {workshop_id: workshop.to_param}, valid_session
      expect(assigns(:student_survey)).to be_a_new(StudentSurvey)
    end
  end

=begin
  describe "GET #edit" do
    it "assigns the requested student_survey as @student_survey" do
      student_survey = StudentSurvey.create! valid_attributes
      get :edit, {:id => student_survey.to_param}, valid_session
      expect(assigns(:student_survey)).to eq(student_survey)
    end
  end
=end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new StudentSurvey" do
        Enrollment.create!(workshop: workshop, student: @student)
        expect {
          post :create, {workshop_id: workshop.to_param, :student_survey => valid_attributes}, valid_session
        }.to change(StudentSurvey, :count).by(1)
      end

      it "assigns a newly created student_survey as @student_survey" do
        Enrollment.create!(workshop: workshop, student: @student)
        post :create, {workshop_id: workshop.to_param, :student_survey => valid_attributes}, valid_session
        expect(assigns(:student_survey)).to be_a(StudentSurvey)
        expect(assigns(:student_survey)).to be_persisted
      end

      it "redirects to the created student_survey" do
        Enrollment.create!(workshop: workshop, student: @student)
        post :create, {workshop_id: workshop.to_param, :student_survey => valid_attributes}, valid_session
        expect(response).to redirect_to(StudentSurvey.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved student_survey as @student_survey" do
        post :create, {workshop_id: workshop.to_param, :student_survey => invalid_attributes}, valid_session
        expect(assigns(:student_survey)).to be_a_new(StudentSurvey)
      end

      it "re-renders the 'new' template" do
        post :create, {workshop_id: workshop.to_param, :student_survey => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

=begin
  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested student_survey" do
        student_survey = StudentSurvey.create! valid_attributes
        put :update, {:id => student_survey.to_param, :student_survey => new_attributes}, valid_session
        student_survey.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested student_survey as @student_survey" do
        student_survey = StudentSurvey.create! valid_attributes
        put :update, {:id => student_survey.to_param, :student_survey => valid_attributes}, valid_session
        expect(assigns(:student_survey)).to eq(student_survey)
      end

      it "redirects to the student_survey" do
        student_survey = StudentSurvey.create! valid_attributes
        put :update, {:id => student_survey.to_param, :student_survey => valid_attributes}, valid_session
        expect(response).to redirect_to(student_survey)
      end
    end

    context "with invalid params" do
      it "assigns the student_survey as @student_survey" do
        student_survey = StudentSurvey.create! valid_attributes
        put :update, {:id => student_survey.to_param, :student_survey => invalid_attributes}, valid_session
        expect(assigns(:student_survey)).to eq(student_survey)
      end

      it "re-renders the 'edit' template" do
        student_survey = StudentSurvey.create! valid_attributes
        put :update, {:id => student_survey.to_param, :student_survey => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested student_survey" do
      student_survey = StudentSurvey.create! valid_attributes
      expect {
        delete :destroy, {:id => student_survey.to_param}, valid_session
      }.to change(StudentSurvey, :count).by(-1)
    end

    it "redirects to the student_surveys list" do
      student_survey = StudentSurvey.create! valid_attributes
      delete :destroy, {:id => student_survey.to_param}, valid_session
      expect(response).to redirect_to(student_surveys_url)
    end
  end
=end

end
